name: CI + Deploy GitHub Pages

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Mensagem:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer o git clone
        uses: actions/checkout@v4

      - name: Executando primeiro comando
        run: |
          ls -l
          echo "Fim do Processo"

  deploy:
    if: github.event_name != 'pull_request'
    needs: Mensagem

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  DOCKER_Login:
      needs: Mensagem
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_SENHA }}
        - name: Build and push Docker images
          uses: docker/build-push-action@v7.4.0
          with:
            file: dockerfile
            push: true
            tags: natybastazini/img_revolucao:1.0
          
